name: Biome Auto-format & Lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: biome-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  biome:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history for proper commits
          fetch-depth: 0
          # Use a PAT or the default GITHUB_TOKEN
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome format
        run: bunx @biomejs/biome format --write .

      - name: Run Biome lint
        run: bunx @biomejs/biome lint --apply .

      - name: Check for changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: auto-format and lint with Biome [skip ci]"
          git push

      - name: Run Biome check
        run: bun biome check

      - name: Run tests
        run: bun test
